### ISSUE TITLE
`test/meson.build:16:2: ERROR: File test_CapRTL_isolate.input does not exist.`

### ISSUE THREAD

**Issue by paulmenzel** [fribidi/fribidi#78] opened 2018-05-16 13:31 UTC
Trying to configure FriBidi 1.0.2 with Meson fails like below.

```
$ meson --prefix /usr --sysconfdir=/etc --localstatedir=/var --buildtype=plain /dev/shm/bee-root/fribidi/fribidi-1.0.2-0/source
The Meson build system
Version: 0.45.1
Source dir: /dev/shm/bee-root/fribidi/fribidi-1.0.2-0/source
Build dir: /dev/shm/bee-root/fribidi/fribidi-1.0.2-0/build
Build type: native build
Project name: fribidi
Native C compiler: cc (gcc 7.3.0 "cc (GCC) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports argument -ansi: YES
Compiler for C supports argument -fvisibility=hidden: YES
Checking for function "memmove": YES
Checking for function "memset": YES
Checking for function "strdup": YES
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "memory.h": YES
Has header "strings.h": YES
Has header "sys/times.h": YES
Has header "strings.h": YES
Configuring config.h using configuration
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "strings.h": YES
Checking for size of "int": 4
Configuring fribidi-config.h using configuration
Program test-runner.py found: YES (/dev/shm/bee-root/fribidi/fribidi-1.0.2-0/source/test/test-runner.py)

test/meson.build:16:2: ERROR: File test_CapRTL_isolate.input does not exist.

A full log can be found at /dev/shm/bee-root/fribidi/fribidi-1.0.2-0/build/meson-logs/meson-log.txt
```

The log files has no additional information regarding the error.

**Comment by tp-m** [comment] 2018-05-16 13:38
I believe this is a duplicate of #74 and is already fixed in git master.

@khaledhosny - a 1.0.3 release tarball with the fix would be nice :)

**Comment by dov** [comment] 2018-05-16 13:42
Right. Forgot about it. I'll see to it tonight.

**Closed** 2018-05-16 17:53 UTC
